### PR TITLE
remaining-clock-time code in cbox.usr

### PR DESCRIPTION
**Pull request by paugier**
With this PR and the last version of snek5000 (in the repo), one should be able to run:

```sh
sim.output.remaining_clock_time.plot()
```

Very useful for long simulations...

cc @akhoubani

### CODE REVIEW

**Comment by paugier** [comment]
@akhoubani could you just confirm that this works for you?

**Comment by akhoubani** [comment]
> @akhoubani could you just confirm that this works for you?

`sim.output.remaining_clock_time.plot()`  gives the error:

```python
OSError: No file /home/arman/Sim_data/examples_cbox/simple/SW/cbox_Ra1.860e+08_64x64_8x8_V1.x1._2023-01-20_10-56-05/remaining_clock_time.csv
```
While I have `remaining_clock_time.csv` file in the `session` directory. It is not looking into the session directory to load it.

**Comment by paugier** [comment]
Ah this is strange. Which command(s) did you run to get that? Here, the file `remaining_clock_time.csv` is not in the session directory.

I tried with `doc/examples/run_side_simple.py`, `doc/examples/run_side_short.py` and `snek-restart`.

**Comment by akhoubani** [comment]
I tried `doc/examples/run_side_short.py`, and then in the simulation directory, `snek-ipy-load`.

**Comment by paugier** [comment]
It is really surprising... Can you paste something equivalent to this ?
```
pierre@gre ~/Dev/snek5000-cbox/doc/examples remaining-clock-time $ python run_side_short.py
[...]
/data0/Sim_data/examples_cbox/simple/SW/cbox_Ra1.860e+08_64x64_8x8_V1.x1._2023-01-20_13-08-49
[Fri Jan 20 13:09:49 2023]
Finished job 0.
7 of 7 steps (100%) done
Complete log: .snakemake/log/2023-01-20T130849.658299.snakemake.log

pierre@gre ~/Dev/snek5000-cbox/doc/examples remaining-clock-time $ ls /data0/Sim_data/examples_cbox/simple/SW/cbox_Ra1.860e+08_64x64_8x8_V1.x1._2023-01-20_13-0
8-49
SESSION.NAME  cbox.box      cbox.par          info_solver.xml   map_user_params.json  remaining_clock_time.csv  rs6cbox0.f00004  templates
SIZE          cbox.log      cbox.re2          logs              nek5000               rs6cbox0.f00001           rs6cbox0.f00005  toolbox
Snakefile     cbox.ma2      cbox.usr          makefile          obj                   rs6cbox0.f00002           rs6cbox0.f00006
build.log     cbox.nek5000  config_simul.yml  makefile_usr.inc  params_simul.xml      rs6cbox0.f00003           session_00

pierre@gre ~/Dev/snek5000-cbox/doc/examples remaining-clock-time $ ls /data0/Sim_data/examples_cbox/simple/SW/cbox_Ra1.860e+08_64x64_8x8_V1.x1._2023-01-20_13-0
8-49/session_00/
cbox.his      cbox0.f00005  cbox0.f00013  cbox0.f00021  cbox0.f00029  cbox0.f00037  cbox0.f00045  cbox0.f00053  cbox0.f00061  cbox0.f00069  cbox0.f00077
cbox.ma2      cbox0.f00006  cbox0.f00014  cbox0.f00022  cbox0.f00030  cbox0.f00038  cbox0.f00046  cbox0.f00054  cbox0.f00062  cbox0.f00070  cbox0.f00078
cbox.par      cbox0.f00007  cbox0.f00015  cbox0.f00023  cbox0.f00031  cbox0.f00039  cbox0.f00047  cbox0.f00055  cbox0.f00063  cbox0.f00071  cbox0.f00079
cbox.re2      cbox0.f00008  cbox0.f00016  cbox0.f00024  cbox0.f00032  cbox0.f00040  cbox0.f00048  cbox0.f00056  cbox0.f00064  cbox0.f00072  cbox0.f00080
cbox0.f00001  cbox0.f00009  cbox0.f00017  cbox0.f00025  cbox0.f00033  cbox0.f00041  cbox0.f00049  cbox0.f00057  cbox0.f00065  cbox0.f00073  cbox0.f00081
cbox0.f00002  cbox0.f00010  cbox0.f00018  cbox0.f00026  cbox0.f00034  cbox0.f00042  cbox0.f00050  cbox0.f00058  cbox0.f00066  cbox0.f00074
cbox0.f00003  cbox0.f00011  cbox0.f00019  cbox0.f00027  cbox0.f00035  cbox0.f00043  cbox0.f00051  cbox0.f00059  cbox0.f00067  cbox0.f00075
cbox0.f00004  cbox0.f00012  cbox0.f00020  cbox0.f00028  cbox0.f00036  cbox0.f00044  cbox0.f00052  cbox0.f00060  cbox0.f00068  cbox0.f00076
```

**Comment by akhoubani** [comment]
```shell
#  nid       tusbc       tdadd       tcrsl       tvdss       tdsum        tgop    qqq    F
           0  7.4839E-01  1.8664E+00  3.6109E-01  2.9359E-01  1.8065E+00  1.3523E+00 qqq
           1  7.7604E-01  1.8499E+00  3.5253E-01  2.3512E-01  1.7624E+00  2.2390E+00 qqq
  
run successful: dying ...
  
  
total elapsed time             :   7.44423E+01 sec
total solver time w/o IO       :   7.43641E+01 sec
time/timestep                  :   6.12655E-03 sec
avg throughput per timestep    :   2.65157E+05 gridpts/CPUs
total max memory usage         :   5.02702E-02 GB

/home/arman/Sim_data/examples_cbox/simple/SW/cbox_Ra1.860e+08_64x64_8x8_V1.x1._2023-01-20_12-19-54
[Fri Jan 20 12:21:24 2023]
Finished job 0.
7 of 7 steps (100%) done
Complete log: .snakemake/log/2023-01-20T121954.406404.snakemake.log

~/Sim_data/examples_cbox/simple/SW/cbox_Ra1.860e+08_64x64_8x8_V1.x1._2023-01-20_12-19-54/session_00$ ls
cbox0.f00001  cbox0.f00009  cbox0.f00017  cbox0.f00025  cbox0.f00033  cbox0.f00041  cbox0.f00049  cbox0.f00057  cbox0.f00065  cbox0.f00073  cbox0.f00081              rs6cbox0.f00002
cbox0.f00002  cbox0.f00010  cbox0.f00018  cbox0.f00026  cbox0.f00034  cbox0.f00042  cbox0.f00050  cbox0.f00058  cbox0.f00066  cbox0.f00074  cbox.his                  rs6cbox0.f00003
cbox0.f00003  cbox0.f00011  cbox0.f00019  cbox0.f00027  cbox0.f00035  cbox0.f00043  cbox0.f00051  cbox0.f00059  cbox0.f00067  cbox0.f00075  cbox.ma2                  rs6cbox0.f00004
cbox0.f00004  cbox0.f00012  cbox0.f00020  cbox0.f00028  cbox0.f00036  cbox0.f00044  cbox0.f00052  cbox0.f00060  cbox0.f00068  cbox0.f00076  cbox.nek5000              rs6cbox0.f00005
cbox0.f00005  cbox0.f00013  cbox0.f00021  cbox0.f00029  cbox0.f00037  cbox0.f00045  cbox0.f00053  cbox0.f00061  cbox0.f00069  cbox0.f00077  cbox.par                  rs6cbox0.f00006
cbox0.f00006  cbox0.f00014  cbox0.f00022  cbox0.f00030  cbox0.f00038  cbox0.f00046  cbox0.f00054  cbox0.f00062  cbox0.f00070  cbox0.f00078  cbox.re2
cbox0.f00007  cbox0.f00015  cbox0.f00023  cbox0.f00031  cbox0.f00039  cbox0.f00047  cbox0.f00055  cbox0.f00063  cbox0.f00071  cbox0.f00079  remaining_clock_time.csv
cbox0.f00008  cbox0.f00016  cbox0.f00024  cbox0.f00032  cbox0.f00040  cbox0.f00048  cbox0.f00056  cbox0.f00064  cbox0.f00072  cbox0.f00080  rs6cbox0.f00001

~/Sim_data/examples_cbox/simple/SW/cbox_Ra1.860e+08_64x64_8x8_V1.x1._2023-01-20_12-19-54/session_00$ snek-ipy-load
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 15:55:03) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.8.0 -- An enhanced Interactive Python. Type '?' for help.
Using matplotlib backend: QtAgg
Loading simulation
path_run: /home/arman/Sim_data/examples_cbox/simple/SW/cbox_Ra1.860e+08_64x64_8x8_V1.x1._2023-01-20_12-19-54
INFO     session_id: 0                                                                                                                                                                                     
INFO     sim:                        <class 'snek5000_cbox.solver.SimulCbox'>                                                                                                                              
         sim.oper:                   <class 'snek5000.operators.Operators'>                                                                                                                                
         sim.output.print_stdout:    <class 'snek5000.output.print_stdout.PrintStdOut'>                                                                                                                    
         sim.output.phys_fields:     <class 'snek5000.output.phys_fields.PhysFields'>                                                                                                                      
         sim.output.history_points:  <class 'snek5000.output.history_points.HistoryPoints'>                                                                                                                
         sim.output.remaining_clock_time: <class 'snek5000.output.remaining_clock_time.RemainingClockTime'>                                                                                                
         sim.output:                 <class 'snek5000_cbox.output.OutputCbox'>                                                                                                                             
         sim.make:                   <class 'snek5000.make.Make'>                                                                                                                                          
                                                                                                                                                                                                           
`sim`, `params`, `np`, `plt` and `pd` variables are available

In [1]: sim.output.remaining_clock_time.plot()
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[1], line 1
----> 1 sim.output.remaining_clock_time.plot()

File ~/Dev/tmp/snek5000/src/snek5000/output/remaining_clock_time.py:47, in RemainingClockTime.plot(self)
     46 def plot(self):
---> 47     self.plot_clock_times()

File ~/mambaforge/envs/env-snek/lib/python3.9/site-packages/fluidsim_core/output/remaining_clock_time.py:26, in RemainingClockTime.plot_clock_times(self)
     23 def plot_clock_times(self):
     24     """Plot the estimated full clock time and clock time per time step."""
---> 26     results = self._load_times()
     27     equation_times = results["equation_times"]
     29     if len(equation_times) == 0:

File ~/Dev/tmp/snek5000/src/snek5000/output/remaining_clock_time.py:19, in RemainingClockTime._load_times(self)
     18 def _load_times(self):
---> 19     df = self.load()
     20     data = {key: df[key].values for key in df.keys()}
     21     data["full_clock_time"] = np.nansum(data["delta_clock_times"])

File ~/Dev/tmp/snek5000/src/snek5000/output/remaining_clock_time.py:28, in RemainingClockTime.load(self)
     25 def load(self):
     27     if not self.path_file.exists():
---> 28         raise IOError(
     29             f"No file {self.path_file}. "
     30             "Is it saved by a function in the .usr file? "
     31             "See https://github.com/snek5000/snek5000/blob/main/docs/examples/snek5000-tgv/src/snek5000_tgv/tgv.usr.f"
     32         )
     34     df = super().load()
     35     df["delta_equation_times"] = df.equation_times.diff()

OSError: No file /home/arman/Sim_data/examples_cbox/simple/SW/cbox_Ra1.860e+08_64x64_8x8_V1.x1._2023-01-20_12-19-54/remaining_clock_time.csv. Is it saved by a function in the .usr file? See https://github.com/snek5000/snek5000/blob/main/docs/examples/snek5000-tgv/src/snek5000_tgv/tgv.usr.f
```

**Comment by paugier** [comment]
The explanation of the difference of behavior: https://github.com/snek5000/snek5000/issues/270

**Comment by paugier** [comment]
I think we can merge like this. Just be careful to use Nek5000 with commit "Adds flags for Intel ifx compiler. (#786)"

- git node: 82a24a55e278628fc3db56de89c8692a519bf6be 
- hg  node: 054d24e171d2264c7150fa5c4f8cd63db50901e7

For example, with Mercurial: `hg up 054d24e171d2264c7150fa5c4f8cd63db50901e7`

**Comment by akhoubani** [comment]
Thanks @paugier !

**Pull request merged**
